language: java
jdk:
- oraclejdk8

after_success:
- ./deploy.sh

notifications:
  slack:
    secure: CtXctRG0nK/1jMasVs8Zj03tSDVX4HI28Ih/4F2g08IOo4L7eCiqPewjEs3vlKHNa3d2Znmc5qFwWaKRZpPNFLtS0T+CiiQVj3IIOk2llyyj5L6s9dnGKfCEedDZjVDaIiGWnVYdwCFrtqt9mIURynQqRwzx/40EhEoyxVA8PU5hKSFPMdlNjSYCi6XjR/IYeiGrrQzCBdwmGIOfl0G0DTGrXx3SYAQJThWGlzN5IJN+6JoMk2qT1d0BPywhOZDQaSJfWuS3ro4w4pKLxf+gaOvbUEbSfYao4M1LaVcrqIEkGPFqGspZOkDaFNCOaIR2XWG03H9+hFkwa7zEULwnLG1QK2mqa/WQyaZke7pOYWQzxh034hROZ1XsZrUtdh2Dn7CDq/0nde2HuRTHj2aM5V5HB5amT7QCiOxKCvaztlU+g+ylbfqv5sO8wGvsYg6aN/FmPfhs6igp7/NDutpkpRvj4haTttV3xutphgGoukRhGeCXZGQgLUomXKdxI+EeXQIL6DKtvGl39PWn+uJiizyPs3Mu0Yg/tgREdiBQeuB0cxcM4R6VLBNHfReh00/5noYQaswh+wiohbSJlWK0vdc59LVWPzgdhNgO/vwVTMq0sHFSBjUfiEUbIsyphsanerdVj/rWCHMsBszeSgqdw4ToMWYEJ2Xa0T3PJqONL+0=
